### ISSUE TITLE
new password not shown in list of passwords

### ISSUE THREAD

**Issue by pern78** [KneeDeepInMud/fortGnox#35]
Windows10/fortGnox1.0.7
Issue: Atfer creating a new password, the file is not shown in the lists of passwords until fortgnox has been restarted. 
Expected behaviour: fortGnox should show newly created password files immediately

**Comment by KneeDeepInMud** [comment]
> Windows10/fortGnox1.0.7 Issue: Atfer creating a new password, the file is not shown in the lists of passwords until fortgnox has been restarted. Expected behaviour: fortGnox should show newly created password files immediately

is the `data directory`, i.e. the directory containing the gpg files, a native local hard disk drive, or any special filesystem (cryptomator, network drive etc?)?

**Comment by KneeDeepInMud** [comment]
Issue could be reproduced on Windows using a mapped network drive. It looks like the `WatchService`  has issues on Windows in at least some Java versions, e.g. https://bugs.openjdk.org/browse/JDK-8227667

    java.io.IOException: Unzulässige Funktion.

        at java.base/sun.nio.fs.WindowsWatchService$Poller.implRegister(WindowsWatchService.java:434)
        at java.base/sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:265)
        at java.base/sun.nio.fs.WindowsWatchService$Poller.run(WindowsWatchService.java:596)
        at java.base/java.lang.Thread.run(Thread.java:835)


Thanks to @pern78 for reporting this :+1:

**Comment by KneeDeepInMud** [comment]
Workaround: use `C:\users\...` as data directory until fixed

**Comment by KneeDeepInMud** [comment]
Should be fixed in v1.0.8
