### ISSUE TITLE
Settings lost after installation of version 1.0alpha5

### ISSUE THREAD

**Issue by samo-20** [KneeDeepInMud/fortGnox#7]

**Comment by KneeDeepInMud** [comment]
Hi samo,

war die vorher installierte Version  schon eine _fortGnox_ oder noch eine _jgpg_ Version?

**Comment by KneeDeepInMud** [comment]
Es wird jetzt angeboten Preferences einer vergabgenen Version zu importieren.
In der neuen Version hat sich der Preference Node wieder geaendert, kannste gleich mal testen, ob es jetzt funktioniert ;-)
